import java.util.Scanner;

public class forstudent3 {

	public static void main(String[] args) {
		// TODO Autogenerated method stub
		
				String studentNumber;
				String name;
				int lang;
				int english;
				int math;
				int sum;
				float average;
				String grade = null;
				
				/*Scanner in = new Scanner(System.in);
				System.out.println("학번을 입력하세요");
				studentNumber = in.next();
				System.out.println("이름을 입력하세요");
				name = in.next();
				System.out.println("언어 점수을 입력하세요");
				lang = in.nextInt();
				System.out.println("영어 점수를 입력하세요");
				english = in.nextInt();
				System.out.println("수학 점수를 입력하세요");
				math = in.nextInt();*/
				
				studentNumber = "ab1";
				name = "dongom";
				lang = 90;
				english = 91;
				math = 93;
				
				sum = lang + english + math;
				average = sum/3;

				//grade = (average >= 90) ? "수" :((average >= 80) ? "우" : "미") ;
				
				/*String StrAverage = String.valueOf(average);
				char firstOfAverage = StrAverage.charAt(0);
				System.out.println(firstOfAverage);*/
				//위는 내 답
				
				int firstOfAverage = (int)average/10;
				
				switch(firstOfAverage) {
				case 10 :
				case 9 :
					grade = "수";
					break;
				case 8 :
					grade = "우";
					break;
				case 7 :
					grade = "미";
					break;
				case 6 :
					grade = "양";
					break;
				default :
					grade = "가";
					break;
				}
				
				/*if(average >= 90) {
					grade = "수";
				}
				else if(average >= 80) {
					grade = "우";
				}
				else if(average >= 70) {
					grade = "미";
				}
				else if(average >= 60) {
					grade = "양";
				}
				else {
					grade = "가";
				}*/
				
				String format = "%-15s%-15s%-15s%-15s%-15s%-15s%-15s%-15s\n";
				//String detailFormat = "'number','name', 'lang', 'engl', 'math', 'sum', 'average', 'grade'";
				//String detailFormat = "\"number\",\"name\", \"lang\", \"engl\", \"math\", \"sum\", \"average\", \"grade\"";

				System.out.println("\t\t\t\t\t\t\t*** 성적표 ***");
				System.out.println("=======================================================================================================================");
//				System.out.printf("%-15s%-15s%-15s%-15s%-15s%-15s%-15s%-15s\n", "number","name", "lang", "engl", "math", "sum", "average", "grade");
				System.out.printf(format, "number","name", "lang", "engl", "math", "sum", "average", "grade");
				//System.out.printf(format, detailFormat);
				//System.out.printf("%15s  %15s   %15s   %15s   %15s   %15s   %15s   %15s\n", "학번","이름", "국어", "영어", "수학", "총점", "평균", "등급");
				System.out.println("=======================================================================================================================");
				System.out.printf("%-15s%-15s%-15d%-15d%-15d%-15d%-15.1f%-15s\n", studentNumber, name, lang, english, math, sum, average, grade);
				//System.out.printf("%10s  %15s   %15d   %15d   %15d   %15d   %15.1f   %15s\n", studentNumber, name, lang, english, math, sum, average, grade);
	}
}
